# numpy
its fast,also performance is greater ....also useful for dot product of arrays


In [4]:
import numpy as np


In [13]:
arr1 = list(range(1000000))
arr2 =list(range(1000000,2000000))
#numpy arrays:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [19]:
%time      #computed time for multiplying two arrays using for loop
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: total: 0 ns
Wall time: 0 ns


833332333333500000

In [21]:
%time
np.dot(arr1_np,arr2_np)     #using numpy array

CPU times: total: 0 ns
Wall time: 0 ns


-1942957984

numpy array using list

In [5]:
a = np.array([8,9,90,67,88],dtype='f') #datatype is defined as a float it can be defined acc to data containing in array 
print(a)             #1st list we have ,it has to convert into numpy array            

[ 8.  9. 90. 67. 88.]


numpy array using tuple

In [6]:
b = np.array((8,9,90,67,88))   #can define in this way also
print(b)              #datatype is optional

[ 8  9 90 67 88]


In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

numpy.ndarray

In [9]:
b.dtype

dtype('int32')

In [10]:
a.dtype

dtype('float32')

multidimentional array

In [11]:
m = np.array([[7,9,0],[8,6,4]])

In [12]:
m.ndim

2

In [13]:
m[0,1]      #1st array 2nd element

9

In [14]:
p = np.array([[7,9,0],[8,6,4],[80,90,70]])   #each array should have same number of elem

In [15]:
p.ndim

2

In [16]:
p[1,2]

4

In [17]:
u = np.array([[[7,8,90],[80,5,34],[35,77,12]],[[89,56,34],[-7,-45,-70],[77,55,44]]])

In [18]:
u[0][1][1]    #3 dimentional array 1st nd array, 2nd array, 1st element

5

In [19]:
u[1][2][2]

44

In [20]:
u.ndim

3

In [21]:
u.shape      #2 2d array 3 lists 3 elements

(2, 3, 3)

In [22]:
type(u)

numpy.ndarray

In [23]:
u.shape[0]       #2 2d arrays

2

In [24]:
u.size #total no. of eleme

18

In [25]:
u.nbytes #no of bytes taking in memory

72

In [28]:
A = np.arange(80)  #creates 1d array in our mentioned range


In [29]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [32]:
K = np.arange(4,90)    #from 4 to 90

In [33]:
K

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89])

In [34]:
K = np.arange(4,90,2)  #2 steps
print(K)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


In [40]:
print(list(range(10)))       #list of 10 range

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [48]:
d = np.random.permutation(np.arange(10)) #shuffle number in random order

In [49]:
d

array([1, 8, 2, 5, 9, 0, 6, 4, 7, 3])

In [52]:
np.random.randint(34,50) #return any random no.between 34 50

38

point to be noted: if single elem in array is floating elem then all elem get converted to float

In [55]:
s = np.random.rand(2,3) #2 by 3 matrix 

In [56]:
s

array([[0.45672202, 0.33922283, 0.13757445],
       [0.56498751, 0.12237826, 0.97403411]])

In [64]:
d = np.random.rand(2,3,4,2)     #2 arrays of 3dim each 3 dim array has 3 2 dim arrays each 2 dim array has 4 1d arrays and each 1d array has 2ele in it  


In [70]:
d
#d.ndim

array([[[[0.23910669, 0.96147908],
         [0.28379101, 0.38136022],
         [0.59010098, 0.96153362],
         [0.9314991 , 0.65269996]],

        [[0.3242805 , 0.35537928],
         [0.29826567, 0.30962382],
         [0.29668074, 0.28241892],
         [0.97328464, 0.91891337]],

        [[0.21270477, 0.14415603],
         [0.60203173, 0.10237951],
         [0.01518225, 0.21627054],
         [0.19908404, 0.09075899]]],


       [[[0.74244637, 0.48319697],
         [0.67257646, 0.7282117 ],
         [0.84209297, 0.62565261],
         [0.40788365, 0.83176701]],

        [[0.30111399, 0.78586381],
         [0.51191204, 0.29167418],
         [0.98718624, 0.43837864],
         [0.85177298, 0.10778277]],

        [[0.62466911, 0.00864826],
         [0.44708368, 0.34374949],
         [0.11809498, 0.27739569],
         [0.32165537, 0.7367584 ]]]])

In [72]:
g = np.arange(60).reshape(4,15)

In [73]:
g

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [74]:
g.shape

(4, 15)

In [77]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

inbuilt function for matrix multipliaction

In [27]:
s =np.random.rand(2,3)
s

array([[0.44142391, 0.36367582, 0.44772515],
       [0.27149471, 0.79887482, 0.53743679]])

In [28]:
l =np.random.rand(3)
l

array([0.55998823, 0.05537716, 0.20708606])

In [29]:
np.matmul(s,l)

array([0.36004917, 0.30756893])

In [30]:
s @ l   #represents matrix multiplication in numpy

array([0.36004917, 0.30756893])

slicing

slicing in numpy uses same memory of given array ..it doesent create copy but creates view...this is big diff in ordinary list or data structure and numpy array

In [102]:
A = np.random.rand(5)

In [103]:
A

array([0.28562512, 0.74366759, 0.2884532 , 0.97988879, 0.89708186])

In [104]:
B = A[2:5]

In [105]:
B

array([0.2884532 , 0.97988879, 0.89708186])

In [106]:
B[0]=  67

In [107]:
B

array([67.        ,  0.97988879,  0.89708186])

In [109]:
A      #value also added in A also    

array([ 0.28562512,  0.74366759, 67.        ,  0.97988879,  0.89708186])

In [114]:
A = np.random.rand(5,4)

In [115]:
A

array([[0.83525348, 0.02845568, 0.17935444, 0.13702089],
       [0.54541789, 0.76303312, 0.51644767, 0.42883175],
       [0.96883013, 0.89098209, 0.35785966, 0.2527409 ],
       [0.49472756, 0.15355181, 0.82844038, 0.0985133 ],
       [0.24198039, 0.72477029, 0.58601535, 0.12932408]])

In [116]:
D = A[2:4]

In [117]:
D

array([[0.96883013, 0.89098209, 0.35785966, 0.2527409 ],
       [0.49472756, 0.15355181, 0.82844038, 0.0985133 ]])

In [118]:
#if we dont want view then create copy b = A[3:10].copy()

In [5]:
#index of any element
S = np.arange(30)
S

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
index = np.argwhere(S==17)  #where is elem 17   #if 2d array is there then add [0][0] in front of(s==17)

In [11]:
index

array([[17]], dtype=int64)

In [22]:
S = np.round(10*np.random.rand(5,6))   #scales values upto 10 and randomly arrange them and rounds values to int

In [23]:
S

array([[9., 8., 9., 1., 1., 1.],
       [9., 7., 3., 9., 5., 2.],
       [5., 1., 0., 5., 1., 6.],
       [6., 0., 2., 7., 2., 3.],
       [4., 5., 7., 1., 9., 5.]])

In [25]:
#access
S[4,1]

5.0

In [26]:
S[1,:]  #all whole row

array([9., 7., 3., 9., 5., 2.])

In [27]:
S[:,1]    #all whole colm

array([8., 7., 1., 0., 5.])

In [32]:
S[1:3,3:5]  #consider 1:3 rows(excluded) and 3:5(excluded)colm for submatrix

array([[9., 5.],
       [5., 1.]])

In [33]:
S.T   #transpose

array([[9., 9., 5., 6., 4.],
       [8., 7., 1., 0., 5.],
       [9., 3., 0., 2., 7.],
       [1., 9., 5., 7., 1.],
       [1., 5., 1., 2., 9.],
       [1., 2., 6., 3., 5.]])

library for linear library

In [34]:
import numpy.linalg as la

In [37]:
la.inv(np.random.rand(3,3))    #inverse of matrix

array([[  2.0752672 ,  10.54756446, -10.0841629 ],
       [ -1.55754163,  -3.55929136,   5.07454525],
       [  0.90196621,  -4.39645471,   3.17373847]])

In [38]:
S.sort(axis=0)   #sorted colm

In [39]:
S

array([[4., 0., 0., 1., 1., 1.],
       [5., 1., 2., 1., 1., 2.],
       [6., 5., 3., 5., 2., 3.],
       [9., 7., 7., 7., 5., 5.],
       [9., 8., 9., 9., 9., 6.]])

In [40]:
S.sort(axis=1) #sorted rows

In [41]:
S

array([[0., 0., 1., 1., 1., 4.],
       [1., 1., 1., 2., 2., 5.],
       [2., 3., 3., 5., 5., 6.],
       [5., 5., 7., 7., 7., 9.],
       [6., 8., 9., 9., 9., 9.]])

numpy more indexing

In [42]:
S[1,3]

2.0

In [43]:
F = np.arange(20)

In [44]:
F

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
R = F[F>10]

In [52]:
R

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
F

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
R = F[(F<20) & (F>10)]

In [58]:
R

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
#  & is used for arrays, and is used for single object  
# | for arrays ,or for single object
# ~ for arrays ,not for single object

masking

In [15]:
#broadcasting:  this will match the other elem to match dimension of matrix to add matrix of same dim
Matrix = np.round(10*np.random.rand(2,3))
Matrix

array([[ 1.,  2.,  3.],
       [ 2., 10.,  7.]])

In [22]:
Matrix+6        #this is mapping as it has created 3 by 2 matrix of 6 ele in it

array([[ 7.,  8.,  9.],
       [ 8., 16., 13.]])

In [23]:
Matrix+(np.arange(2).reshape(2,1))

array([[ 1.,  2.,  3.],
       [ 3., 11.,  8.]])

In [30]:
#universal functions
#conatenate arrays horrizontally
A = np.round(5*np.random.rand(3,4))
A


array([[3., 0., 5., 0.],
       [0., 1., 0., 0.],
       [5., 4., 4., 3.]])

In [29]:
B = np.round(5*np.random.rand(3,4))
B

array([[1., 3., 4., 1.],
       [1., 4., 3., 4.],
       [0., 0., 1., 1.]])

In [34]:
C = np.hstack((A,B)) #if hosrizontal conact then all  arrays should be in tuple
C

array([[3., 0., 5., 0., 1., 3., 4., 1.],
       [0., 1., 0., 0., 1., 4., 3., 4.],
       [5., 4., 4., 3., 0., 0., 1., 1.]])

In [35]:
C = np.vstack((A,B)) 
C

array([[3., 0., 5., 0.],
       [0., 1., 0., 0.],
       [5., 4., 4., 3.],
       [1., 3., 4., 1.],
       [1., 4., 3., 4.],
       [0., 0., 1., 1.]])

In [42]:
C.sort(axis=1)
C

array([[0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [0., 0., 3., 4.],
       [1., 1., 3., 4.],
       [1., 3., 4., 5.],
       [3., 4., 4., 5.]])

In [44]:
D = np.array([1,2,4,56,7])
D

array([ 1,  2,  4, 56,  7])

In [45]:
np.sort(D)

array([ 1,  2,  4,  7, 56])

how numpy is fast

In [52]:
V = np.random.rand(100000)
%timeit sum(V)     #under python by default function
%timeit np.sum(V)   #under numpy    this is faaster than sum function


13.7 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.4 µs ± 418 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
